### ISSUE TITLE
Missing 'exports' field in package.json

### ISSUE THREAD

**Issue by FazCodeFR** [bcomnes/resolve-email#4]
Hello,
I have a problem, i can't install the package on my project, (nodejs : nestjs & typescript) 

Error: No "exports" main defined in \node_modules\resolve-email\package.json

I can't fix it (junior dev)

Thank you, 
(and a great idea for a package)

**Comment by bcomnes** [comment]
This is an esm only package, so you need to import it with either node.js module mode (typescript makes this more complex, and I don't know the solution off hand) or await import it.

```js
// Inside an async function
const { resolveEmail } = await import('resolve-email')
```

ChatGPT 4 might also be able to help work through the specifics of the issue.

Good luck!
